// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7y_zkMm6hJOX_UHiPQlQy0JV5QYIjoI',
    appId: '1:603091123396:web:0a768bd0f060a701959d91',
    messagingSenderId: '603091123396',
    projectId: 'chattapp-22fff',
    authDomain: 'chattapp-22fff.firebaseapp.com',
    storageBucket: 'chattapp-22fff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnD-0ICxmPskigxfVmXmb45eumI8QDY7E',
    appId: '1:603091123396:android:810b85eaf98d5889959d91',
    messagingSenderId: '603091123396',
    projectId: 'chattapp-22fff',
    storageBucket: 'chattapp-22fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSePsiVeKCTyO6QiQiLb7pg-H0XfUxsFA',
    appId: '1:603091123396:ios:ece075c056e7bc00959d91',
    messagingSenderId: '603091123396',
    projectId: 'chattapp-22fff',
    storageBucket: 'chattapp-22fff.firebasestorage.app',
    androidClientId: '603091123396-pgv5h34co0v6kpl7bs2vdp112tnamp2g.apps.googleusercontent.com',
    iosClientId: '603091123396-00mifpev1khjs3h8qgnt2pi0sv5hjlps.apps.googleusercontent.com',
    iosBundleId: 'com.tes.chat.chatAplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSePsiVeKCTyO6QiQiLb7pg-H0XfUxsFA',
    appId: '1:603091123396:ios:ece075c056e7bc00959d91',
    messagingSenderId: '603091123396',
    projectId: 'chattapp-22fff',
    storageBucket: 'chattapp-22fff.firebasestorage.app',
    androidClientId: '603091123396-pgv5h34co0v6kpl7bs2vdp112tnamp2g.apps.googleusercontent.com',
    iosClientId: '603091123396-00mifpev1khjs3h8qgnt2pi0sv5hjlps.apps.googleusercontent.com',
    iosBundleId: 'com.tes.chat.chatAplikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV7y_zkMm6hJOX_UHiPQlQy0JV5QYIjoI',
    appId: '1:603091123396:web:a7ff08a54f4beee3959d91',
    messagingSenderId: '603091123396',
    projectId: 'chattapp-22fff',
    authDomain: 'chattapp-22fff.firebaseapp.com',
    storageBucket: 'chattapp-22fff.firebasestorage.app',
  );
}
